#ifndef PARSERHELPER_GLOBAL_H
#define PARSERHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PARSERHELPER_LIBRARY)
#  define PARSERHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PARSERHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PARSERHELPER_GLOBAL_H
